name: workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: "set name"
        required: true
        default: "github-actions"
        type: string
      environment:
        description: "set env"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo ${{ inputs.name }}
      - name: step2
        run: echo ${{ inputs.environment }}
