name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "job3 failed"
          exit 1
  job4:
    needs: [job3]
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions
