name: re-run
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions
      - name: cat readme
        run: cat README.md
