name: workflow-dispatch
on:
  workflow_dispatch: 
    inputs: 
      name: 
        description: 'set name' # name이라는 input에 대한 설명
        required: true # input의 필수값 여부
        default: 'github-actions' # input의 기본값
        type: string # 사용할 데이터 타입
      environment: 
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options: 
        - dev
        - qa
        - prod

jobs: 
    workflow-dispatch-job: # 디폴트 브랜치에서만 트리거됨
        runs-on: ubuntu-latest 
        steps: 
        - name: step1
          run: echo hello world
        - name: step2
          run: | 
            echo hello world
            echo github action
        - name: echo inputs
          run: | 
            echo ${{ inputs.name }}
            echo ${{ inputs.environment }}
