name: push-workflow
on: push  
# on: push 이렇게 적으면 push 이벤트에 의해서 워크플로우를 트리거 하겠다는 얘기임
jobs : 
    push-job:
      runs-on: ubuntu-latest
      steps:
        -name:step1
        run: echo hello world
# jobs: 꼭실행되어야하는 job집합
