name: checkout-action
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: cat README.md

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v4
      - name: step2
        run: cat README.md
