name: environment
on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ vars.value }}
          echo ${{ secrets.value }}

  echo2:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo
        run: |
          echo ${{ vars.value }}
          echo ${{ secrets.value }}