name: if-2
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: exit 1
        run: exit 1
      - name: echo hello world
        if: always()
        run: echo hello world

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: echo hello world
        run: echo hello world
