name: path_filter
on:
  push:
    paths:
      - '.github/workflows/part1/*'
      - '!.github/workflows/part1/push.yaml'

jobs:
  echo-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello