name: string-fn
on: push

jobs:
  string-fn:
    runs-on: ubuntu-latest
    steps:
      - name: startswith
        if: startsWith('github action', 'git')
        run: echo "GIT"
      - name: startswith
        if: startsWith('github action', 'test')
        run: echo "TEST"

      - name: endswith
        if: endsWith('github action', 'ion')
        run: echo "ION"
      - name: endswith
        if: endsWith('github action', 'test')
        run: echo "TEST"

      - name: contains
        if: contains('github action', 'act')
        run: echo "ACT"
      - name: contains
        if: contains('github, action', 'git')
        run: echo "GIT"

      - name: test
        if: contains("${{ vars.value }}", "variable")
        run: echo "GOOD"