name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: loop
        timeout-minutes: 1
        run: |
          count=0
          while true; do
            echo "$count seconds"
            count=$((count+1))
            sleep 1
          done
      - name: echo
        run: echo hello