name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
    - 'my-app/**'

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize' 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  image-build:
    if: github.event.pull_request.merged == true #merge단계에서 실행되는 잡 , 즉 cd단계
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
      - name: checkout
        uses: actions/checkout@v4
