name: cicd-1

on:
  workflow_dispatch: 
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
      - '*/**'

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          cd next-app
          npm ci
      - name: Build with npm
        run: |
          cd next-app/cdk
          npm install
          npm run build
      - name: Install CDK dependencies
        run: |
          cd next-app/cdk
          npm install aws-cdk-lib
          npm install -g aws-cdk

  image-build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Install dependencies for Docker
        run: |
          npm ci
          npm install aws-cdk-lib --save-dev
          npm install @aws-cdk/aws-apigatewayv2-integrations-alpha
          npm install @aws-cdk/aws-apigatewayv2-alpha
        working-directory: next-app/
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      - name: Get ECR Repo URL and Image Tag
        run: |
          REPO_URL=$(aws ecr describe-repositories --repository-names hinagiku-dev-ecs-hinagikudevecsapphinagikudevecsbackendbackappecsresourcesrepoce5391e0-lm3igs4fy1sc --query 'repositories[].repositoryUri' --output text)
          echo "REPO_URL=$REPO_URL"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV

          function generate_image_tag() {
            local -r tag=$(tar cf - ./* > /dev/null 2>&1 | md5sum | cut -c 1-8)
            echo "$tag"
          }
          TAG=$(generate_image_tag)
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Prepare Lambda Deployment Package
        run: |
          echo "{\"DOCKER_IMAGE_URL\": \"$REPO_URL\", \"TAG\": \"$TAG\"}" > docker_image_info.json
          cat docker_image_info.json
        working-directory: infra/lambda
      - name: Save environment variables as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker_image_info
          path: infra/lambda/docker_image_info.json
      - name: Docker build & push
        run: |
          docker build -f Dockerfile --tag ${{ env.REPO_URL }}:${{ env.TAG }} .
          docker push ${{ env.REPO_URL }}:${{ env.TAG }}
        working-directory: next-app/

  deploy:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Download environment variables artifact
        uses: actions/download-artifact@v3
        with:
          name: docker_image_info
          path: './infra/lambda'
      - name: Load environment variables
        run: |
          DOCKER_IMAGE_INFO=$(cat ./infra/lambda/docker_image_info.json)
          export REPO_URL=$(echo $DOCKER_IMAGE_INFO | jq -r '.DOCKER_IMAGE_URL')
          export TAG=$(echo $DOCKER_IMAGE_INFO | jq -r '.TAG')
          echo "REPO_URL=$REPO_URL"
          echo "TAG=$TAG"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          export NODE_ENV=development
          npm ci
          npm install aws-cdk-lib --save-dev
          npm install @aws-cdk/aws-apigatewayv2-integrations-alpha
          npm install @aws-cdk/aws-apigatewayv2-alpha
        working-directory: next-app/cdk
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
      - name: Test AWS Credentials
        run: aws sts get-caller-identity
      - name: Get S3 Bucket Name from SSM
        id: get_s3_bucket_name
        run: |
          BUCKET_NAME=$(aws ssm get-parameter --name "/Hinagiku/TriggerBucket/EcsBackend" --query "Parameter.Value" --output text)
          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
          
      - name: List files in infra/lambda
        run: ls -l infra/lambda
        
      - name: Prepare Lambda Deployment Package
        run: |
          cd infra/lambda
          echo "{\"DOCKER_IMAGE_URL\": \"$REPO_URL\", \"TAG\": \"$TAG\"}" > docker_image_info.json
          cat docker_image_info.json
          zip -r image.zip docker_image_info.json lambda_function_config.json ../script/lambda.sh
          ls -l
        working-directory: infra/lambda
      - name: Upload to S3
        run: |
          aws s3 cp image.zip s3://$BUCKET_NAME/image.zip
        working-directory: infra/lambda
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
