name: issue-workflow
on:
  issue:
  types: [opened]
jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: rrrrrrr
    - name: step2
      run: |
        echo Super
        echo Issue