name: push-workflow
on: 
  push:
    branches:
      - '*'  # This will trigger the workflow on push to any branch

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world